import { Layout } from '@/components/layout/Layout';
import { StatCard } from '@/components/cards/StatCard';
import { Button } from '@/components/ui/button';
import { bankrollHistory, summaryStats } from '@/data/mockData';
import { Wallet, TrendingUp, Download, DollarSign, Calendar } from 'lucide-react';
import {
  LineChart,
  Line,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  AreaChart,
  Area,
} from 'recharts';
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import { cn } from '@/lib/utils';
import { toast } from '@/hooks/use-toast';

const Bankroll = () => {
  const chartData = bankrollHistory.map(entry => ({
    ...entry,
    dateShort: entry.date.slice(5),
  }));

  const currentBalance = bankrollHistory[bankrollHistory.length - 1].balance;
  const startingBalance = bankrollHistory[0].balance;
  const totalProfit = currentBalance - startingBalance;
  const totalBets = bankrollHistory.reduce((sum, e) => sum + e.betsPlaced, 0);
  const profitPercent = ((totalProfit / startingBalance) * 100).toFixed(1);

  const handleDownloadCSV = () => {
    const headers = ['Date', 'Balance', 'Bets Placed', 'Daily Profit'];
    const rows = bankrollHistory.map(entry => [
      entry.date,
      entry.balance.toFixed(2),
      entry.betsPlaced,
      entry.profit.toFixed(2),
    ]);

    const csvContent = [headers, ...rows].map(row => row.join(',')).join('\n');
    const blob = new Blob([csvContent], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `bankroll_history_${new Date().toISOString().split('T')[0]}.csv`;
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Download Started",
      description: "Your bankroll history CSV is being downloaded.",
    });
  };

  const handleDownloadSummary = () => {
    const summary = `
NBA PREDICTION BETTING SUMMARY
==============================
Generated: ${new Date().toLocaleDateString()}

BANKROLL OVERVIEW
-----------------
Starting Balance: €${startingBalance.toFixed(2)}
Current Balance: €${currentBalance.toFixed(2)}
Total Profit: €${totalProfit.toFixed(2)} (${profitPercent}%)
Total Bets Placed: ${totalBets}

PERFORMANCE METRICS
-------------------
Overall Accuracy: ${(summaryStats.overallAccuracy * 100).toFixed(0)}%
Total Predictions: ${summaryStats.totalPredictions}
ROI: ${summaryStats.roi}%
Current Win Streak: ${summaryStats.winStreak}

This summary was generated by Basketball Prediction Pipeline 2026.
For educational purposes only. Please gamble responsibly.
    `.trim();

    const blob = new Blob([summary], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `betting_summary_${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast({
      title: "Summary Downloaded",
      description: "Your betting summary has been saved.",
    });
  };

  return (
    <Layout>
      <div className="container mx-auto px-4 py-8">
        {/* Header */}
        <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
          <div>
            <h1 className="text-3xl font-bold mb-2">Bankroll Tracker</h1>
            <p className="text-muted-foreground">
              Monitor your betting performance and download reports
            </p>
          </div>
          <div className="flex gap-3">
            <Button variant="outline" onClick={handleDownloadCSV}>
              <Download className="w-4 h-4 mr-2" />
              Export CSV
            </Button>
            <Button variant="gold" onClick={handleDownloadSummary}>
              <Download className="w-4 h-4 mr-2" />
              Summary
            </Button>
          </div>
        </div>

        {/* Stats Grid */}
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 mb-8">
          <StatCard
            title="Current Balance"
            value={`€${currentBalance.toFixed(0)}`}
            subtitle={`Started: €${startingBalance}`}
            icon={<Wallet className="w-6 h-6" />}
          />
          <StatCard
            title="Total Profit"
            value={`+€${totalProfit.toFixed(0)}`}
            subtitle={`${profitPercent}% return`}
            icon={<DollarSign className="w-6 h-6" />}
            trend="up"
          />
          <StatCard
            title="ROI"
            value={`${summaryStats.roi}%`}
            subtitle="return on investment"
            icon={<TrendingUp className="w-6 h-6" />}
            trend="up"
          />
          <StatCard
            title="Bets Placed"
            value={totalBets}
            subtitle={`${bankrollHistory.length} days tracked`}
            icon={<Calendar className="w-6 h-6" />}
          />
        </div>

        {/* Balance Chart */}
        <div className="glass-card p-6 mb-8">
          <h3 className="font-semibold mb-6">Balance Growth</h3>
          <div className="h-[350px]">
            <ResponsiveContainer width="100%" height="100%">
              <AreaChart data={chartData}>
                <defs>
                  <linearGradient id="balanceGradient" x1="0" y1="0" x2="0" y2="1">
                    <stop offset="5%" stopColor="hsl(38, 92%, 50%)" stopOpacity={0.4} />
                    <stop offset="95%" stopColor="hsl(38, 92%, 50%)" stopOpacity={0} />
                  </linearGradient>
                </defs>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(25, 20%, 20%)" />
                <XAxis 
                  dataKey="dateShort" 
                  stroke="hsl(30, 10%, 55%)"
                  fontSize={12}
                />
                <YAxis 
                  stroke="hsl(30, 10%, 55%)"
                  fontSize={12}
                  tickFormatter={(value) => `€${value}`}
                  domain={['dataMin - 50', 'dataMax + 50']}
                />
                <Tooltip
                  contentStyle={{
                    backgroundColor: 'hsl(20, 8%, 12%)',
                    border: '1px solid hsl(25, 20%, 20%)',
                    borderRadius: '8px',
                  }}
                  labelStyle={{ color: 'hsl(40, 20%, 92%)' }}
                  formatter={(value: number) => [`€${value.toFixed(2)}`, 'Balance']}
                />
                <Area
                  type="monotone"
                  dataKey="balance"
                  stroke="hsl(38, 92%, 50%)"
                  strokeWidth={3}
                  fill="url(#balanceGradient)"
                />
              </AreaChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Transaction History */}
        <div className="glass-card overflow-hidden">
          <div className="p-6 border-b border-border">
            <h3 className="font-semibold">Daily History</h3>
          </div>
          <Table>
            <TableHeader>
              <TableRow className="border-border hover:bg-transparent">
                <TableHead>Date</TableHead>
                <TableHead className="text-right">Balance</TableHead>
                <TableHead className="text-right">Bets</TableHead>
                <TableHead className="text-right">Daily P/L</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {[...bankrollHistory].reverse().map((entry) => (
                <TableRow key={entry.date} className="table-row-hover border-border">
                  <TableCell className="font-medium">{entry.date}</TableCell>
                  <TableCell className="text-right font-mono">
                    €{entry.balance.toFixed(2)}
                  </TableCell>
                  <TableCell className="text-right">{entry.betsPlaced}</TableCell>
                  <TableCell className={cn(
                    "text-right font-semibold",
                    entry.profit >= 0 ? "stat-positive" : "stat-negative"
                  )}>
                    {entry.profit >= 0 ? '+' : ''}€{entry.profit.toFixed(2)}
                  </TableCell>
                </TableRow>
              ))}
            </TableBody>
          </Table>
        </div>

        {/* Disclaimer */}
        <div className="mt-8 p-4 border border-border rounded-lg bg-muted/20">
          <p className="text-sm text-muted-foreground text-center">
            <strong>Disclaimer:</strong> This tool is for educational and informational purposes only. 
            Past performance does not guarantee future results. Always gamble responsibly and never bet more than you can afford to lose.
          </p>
        </div>
      </div>
    </Layout>
  );
};

export default Bankroll;
